### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by samcome** [maximedrn/opensea_automatic_uploader#3]
Hello,

I am not a developer just webdesigner/intégrateur and I tested your script on a mac, 30' for 100 nft's (on average 7Mo/nfts). It works great, thanks (only colorama don't work)! I was wondering if it would be easily adaptable to eg update images and metadata? No longer be in creation mode but edition.
I imagined a mint pre-sale. and from a date upload the final nft ;)

Many thanks for your work!

**Comment by DannyRain** [comment]
It's pretty good! But there are still some deficiencies. 

1. "# Input collection and select it" part seems to be unstable as it always selects the first collection on opensea instead of the one we input. Sometimes it goes wrong like "Collection doesn't exist" even if we input the right collection.
2. I highly suggest that the "nft_sell" part should be an independent part. I guess many people has the requirement that uploading and selling should be executed independently. For example, someone uploaded 100 NFTs on Monday. He might sell 10 NFTs for 0.1 eth on Tuesday. He may sell 15 NFTs for 0.5 eth on Friday. If the uploading part and the selling part are independent, these things will be easy to be executed automatically.

As far as I am concerned, these things matters a lot. Thanks for your contribution!

**Comment by psc215** [comment]
Hello @samcome ,I've been trying for days to get this code to work on a mac. Can you explain in detail what changes you made?

**Comment by maximedrn** [comment]
Hello, I have integrated your functionality in my bot. You can upload and sell your NFTs later. Moreover, I have improved the MacOS support, Colorama is not used when you are on Mac and the webdriver path does not have to be changed anymore.
