### ISSUE TITLE
I use fortmatic 

### ISSUE THREAD

**Issue by Karmaismybtch** [maximedrn/opensea_automatic_uploader#32]
how do I do now?

**Comment by maximedrn** [comment]
For the moment FortMatic is not supported by the bot. You can only use MetaMask.
A support will be published in the following weeks.

**Comment by Karmaismybtch** [comment]
I switched to metamask but and tried to fill the JSON file but after I entered 2 to upload and sell the python window just closed

**Comment by maximedrn** [comment]
Do you have the right version of chromedriver in the `assets/` folder?
If it crashes after selecting the option and the file, it is due to the webdriver part.

NB: it's not that hard for beginners. You just need to know of to structure your metadata file (all is explained) and to follow instructions.

**Comment by Karmaismybtch** [comment]
I updated chromedriver and it's still the same I filled the Excel sheet instead of the json file and picked it and it crashed anyways

**Comment by maximedrn** [comment]
Can you send me a screenshot of the exception printed in the command line.
